Decoded AnimationSystem properties & related structs
WopsS/RED4ext.SDK pull request #139
Opened 2024-07-19 18:01 UTC by Mozz3d

2024-07-19 18:32 UTC, WopsS approved these changes

2024-07-20 08:53 UTC, psiberx requested changes

2024-07-20 08:53 UTC, psiberx commented on include/RED4ext/Scripting/Natives/worldAnimationSystem.hpp
> +};
Please add size assertion here.

2024-07-20 08:53 UTC, psiberx commented on include/RED4ext/Scripting/Natives/worldAnimationSystem.hpp
> +};
And if we use game's namespaces, let's add it to file names as for original classes too, i.e. `animKeyFrames.hpp`, `animAnimatedObject.hpp`, `animMetaRig.hpp`, `animAnimBufferState.hpp`, etc.

2024-07-21 14:59 UTC, psiberx approved these changes

2024-07-22 18:48 UTC, WopsS approved these changes

2024-07-22 18:48 UTC, merged